Combine scripts onto one on saving system.

diff --git a/.local/bin/save_system b/.local/bin/save_system
--- a/.local/bin/save_system
+++ b/.local/bin/save_system
@@ -60,6 +60,49 @@ restore() {
     echo "Restored!"
 }
 
+push_dotfiles() {
+    emacs_dir="$HOME/.config/emacs/"
+    awesome_dir="$HOME/.config/awesome/"
+
+    # From the home directory.
+    cd "$HOME" || {
+        echo "Failed to change to home directory"
+        exit 1
+    }
+
+    echo "Dotfiles pushed from $HOME"
+
+    # Optional: make sure you're on the correct branch
+    # git checkout main
+
+    # Push my Emacs config to the cloud.
+    git push origin HEAD
+
+    cd "$emacs_dir" || {
+        echo "Failed to change to home directory"
+        exit 1
+    }
+
+    git push origin HEAD
+
+    echo "Push Emacs directory."
+}
+
+push_branches() {
+    # Push all local branches to origin
+    for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
+        # TODO: notify me if there is a new remote branch that had to be created and
+        # silence output so I do not have to see everything.
+        if ! git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
+            echo "Creating new remote branch: $branch"
+            git push -u origin "$branch" >/dev/null 2>&1
+        else
+            git push origin "$branch" >/dev/null 2>&1
+        fi
+        echo "Pushing branch: $branch"
+    done
+}
+
 case "$1" in
     "" | backup)
         backup
