Update script.

diff --git a/.local/bin/sync b/.local/bin/sync
--- a/.local/bin/sync
+++ b/.local/bin/sync
@@ -11,7 +11,8 @@ PASSWORD_DIR=".local/share/.password-store"
 PRIVATE_KEY_DIR=".gnupg/private-keys-v1.d"
 # Right now this assumes that I have mounted my external drive to "/mnt/hardrive/".
 DRIVE="/mnt/hardrive"
-BACKUP_DIR="$DRIVE/archlinux-home-12-29-2024"
+BACKUP_DIR="$DRIVE/archlinux-home-$(date +%Y-%m-%d)"
+PRIVATE_SSH_KEY=".ssh/id_rsa"
 
 SOURCES="
 $USER_HOME/Documents
@@ -23,10 +24,11 @@ $USER_HOME/Trash
 $USER_HOME/Audio
 $USER_HOME/$PASSWORD_DIR
 $USER_HOME/$PRIVATE_KEY_DIR
+$USER_HOME/$PRIVATE_SSH_KEY
 "
 
 backup() {
-    echo "Backing up home directories to hardrive"
+    echo "Backing up home directories to $BACKUP_DIRECTORY..."
     # Build the list of excludes to exclude any git repos.
     for SOURCE in $SOURCES; do
         if [ -d "$SOURCE" ]; then
@@ -41,7 +43,7 @@ backup() {
             mkdir -p "$TARGET"
             eval rsync -aAxv $EXCLUDES "$SOURCE/" "$TARGET/" >/dev/null
         else
-            echo "⚠️  Skipping $SOURCE — not a directory or doesn't exist."
+            echo "⚠️ Skipping $SOURCE — not a directory or doesn't exist."
         fi
     done
     echo "Done backing up!"
@@ -60,48 +62,48 @@ restore() {
     echo "Restored!"
 }
 
-push_dotfiles() {
-    emacs_dir="$HOME/.config/emacs/"
-    awesome_dir="$HOME/.config/awesome/"
+# push_dotfiles() {
+#     emacs_dir="$HOME/.config/emacs/"
+#     awesome_dir="$HOME/.config/awesome/"
 
-    # From the home directory.
-    cd "$HOME" || {
-        echo "Failed to change to home directory"
-        exit 1
-    }
+#     # From the home directory.
+#     cd "$HOME" || {
+#         echo "Failed to change to home directory"
+#         exit 1
+#     }
 
-    echo "Dotfiles pushed from $HOME"
+#     echo "Dotfiles pushed from $HOME"
 
-    # Optional: make sure you're on the correct branch
-    # git checkout main
+#     # Optional: make sure you're on the correct branch
+#     # git checkout main
 
-    # Push my Emacs config to the cloud.
-    git push origin HEAD
+#     # Push my Emacs config to the cloud.
+#     git push origin HEAD
 
-    cd "$emacs_dir" || {
-        echo "Failed to change to home directory"
-        exit 1
-    }
+#     cd "$emacs_dir" || {
+#         echo "Failed to change to home directory"
+#         exit 1
+#     }
 
-    git push origin HEAD
+#     git push origin HEAD
 
-    echo "Push Emacs directory."
-}
+#     echo "Push Emacs directory."
+# }
 
-push_branches() {
-    # Push all local branches to origin
-    for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
-        # TODO: notify me if there is a new remote branch that had to be created and
-        # silence output so I do not have to see everything.
-        if ! git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
-            echo "Creating new remote branch: $branch"
-            git push -u origin "$branch" >/dev/null 2>&1
-        else
-            git push origin "$branch" >/dev/null 2>&1
-        fi
-        echo "Pushing branch: $branch"
-    done
-}
+# push_branches() {
+#     # Push all local branches to origin
+#     for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
+#         # TODO: notify me if there is a new remote branch that had to be created and
+#         # silence output so I do not have to see everything.
+#         if ! git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
+#             echo "Creating new remote branch: $branch"
+#             git push -u origin "$branch" >/dev/null 2>&1
+#         else
+#             git push origin "$branch" >/dev/null 2>&1
+#         fi
+#         echo "Pushing branch: $branch"
+#     done
+# }
 
 case "$1" in
     "" | backup)
